### ISSUE TITLE
ecs_services and environment variables

### ISSUE THREAD

**Issue by kvernon** [duplocloud/ghactions-service-update#116]
Howdy team,

Recently I've been trying do deploy using `duplocloud/ghactions-service-update@master`, but looking at the information / example, I can't figure out how to set environment variables. 

Reference in readme.md: https://github.com/duplocloud/ghactions-service-update#example-updating-an-ecs-service

(ref on readme):
```yml
name: Build and Deploy
on:
  push:
    branches:
      - develop # branch to trigger on
jobs:
  deploy:
    # This example updates a service named "nginx" to use an image "nginx:latest"
    name: Deploy with DuploCloud
    runs-on: ubuntu-latest
    steps:
      - name: service-update
        uses: duplocloud/ghactions-service-update@master
        with:
          duplo_host: https://mysystem.duplocloud.net
          duplo_token: ${{ secrets.DUPLO_TOKEN }}
          tenant: default
          ecs_services: |-
            [
              { "Name": "nginx", "Image": "nginx:latest" }
            ]
```

I've tried:

```yml
name: Build and Deploy
on:
  push:
    branches:
      - develop # branch to trigger on
jobs:
  deploy:
    # This example updates a service named "nginx" to use an image "nginx:latest"
    name: Deploy with DuploCloud
    runs-on: ubuntu-latest
    steps:
      - name: service-update
        uses: duplocloud/ghactions-service-update@master
        with:
          duplo_host: https://mysystem.duplocloud.net
          duplo_token: ${{ secrets.DUPLO_TOKEN }}
          tenant: default
          ecs_services: |-
            [{ 
                 "Name": "nginx", 
                 "Image": "nginx:latest",
                 "MY_VAR": "butter"
            }]
```

when I go to look at env vars area, nothing --- of course, this is me trying my best to combine the ideas supplied in the readme, but I'm striking help. 

Any ideas?

Thanks,
Kelly
